<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-B0A316T" name="com.mobiotics.HITSAdmin.tstCases.TC_Report_Core_ListCustomer" tests="1" failures="1" timestamp="26 Jun 2019 08:42:54 GMT" time="76.447" errors="0">
  <testcase name="reportCoreListCustomerTestMethod" time="76.447" classname="com.mobiotics.HITSAdmin.tstCases.TC_Report_Core_ListCustomer">
    <failure type="java.lang.AssertionError" message="Count is displaying wrong number expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: Count is displaying wrong number expected [1] but found [0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.mobiotics.HITSAdmin.ReportCoreListCustomer.ReportCoreListCustomerPage.verifyCount(ReportCoreListCustomerPage.java:202)
at com.mobiotics.HITSAdmin.ReportCoreListCustomer.ReportCoreListCustomerPage.testReportCoreListCustomer(ReportCoreListCustomerPage.java:371)
at com.mobiotics.HITSAdmin.tstCases.TC_Report_Core_ListCustomer.reportCoreListCustomerTestMethod(TC_Report_Core_ListCustomer.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- reportCoreListCustomerTestMethod -->
</testsuite> <!-- com.mobiotics.HITSAdmin.tstCases.TC_Report_Core_ListCustomer -->
